version: "3.9"
services:
  postgres:
    container_name: postgres_db
    restart: always
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "natali"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
